Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [ ]:
class Employee:
    num_employees = 0  # Class variable to count the number of employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1  # Increment the count of employees


    def average_salary(employees):
        total_salary_of_the_employee = sum(emp.salary for emp in employees)
        return total_salary_of_the_employee / len(employees) if len(employees) > 0 else 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


# creating instances for the full time employee as well as the employees of the employee classes
employee_1 = Employee("Jp reddy", "Family 1", 58000, "HR")
employee_2 = Employee("Rao Ramesh", "Family 2", 82000, "Finance")
employee_3 = Employee("Vikas Reddy", "Family 3", 928000, "IT")

fulltime_employee_1 = FulltimeEmployee("George Bailey", "Family 4", 96200, "Marketing")
fulltime_employee_2 = FulltimeEmployee("Browney choan", "Family 5", 85400, "Operations")

# Calling the members of the function
employees = [employee_1, employee_2, employee_3]
employee_2=[fulltime_employee_1, fulltime_employee_2]
avg_salary = Employee.average_salary(employees)
avg_salary_full_time=Employee.average_salary(employee_2)
print(f"Average salary of employee: {avg_salary}")
print(f"Average salary of fulltime employee : {avg_salary_full_time}")

print(f"Total Number of employees: {Employee.num_employees}")


Average salary of employee: 356000.0
Average salary of fulltime employee : 90800.0
Total Number of employees: 5


Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1) (you can NOT implement it via for loop)
Evaluation

In [ ]:
import numpy as np

# Create a random vector of size 20 with integers in the range 1-20
random_matrix = np.round(np.random.uniform(1,20,size=20),1)
print("Original matrix=",random_matrix)

# Here the vector should be replaced in 4x5 matrix conversion
reshaped_matrix = random_matrix.reshape(4, 5)

# Replace the maximum value in each row with 0
max_indices = np.argmax(reshaped_matrix, axis=1)
reshaped_matrix[np.arange(4), max_indices] = 0

# Here the reshaped matrix will be printed
print("\nReshaped matrix:")
print(reshaped_matrix)


Original matrix= [13.1 10.4  1.1 17.5  5.2  3.7 13.1  4.7  1.4  7.1  4.4  5.3  4.5 16.7
 11.4 19.5 16.8  8.5 16.   3. ]

Reshaped matrix:
[[13.1 10.4  1.1  0.   5.2]
 [ 3.7  0.   4.7  1.4  7.1]
 [ 4.4  5.3  4.5  0.  11.4]
 [ 0.  16.8  8.5 16.   3. ]]
